export const GET_CITIES = 'GET_CITIES'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE'

export const GET_TECHNOLOGIES = 'GET_TECHNOLOGIES'
export const GET_TECHNOLOGIES_SUCCESS = 'GET_TECHNOLOGIES_SUCCESS'
export const GET_TECHNOLOGIES_FAILURE = 'GET_TECHNOLOGIES_FAILURE'